### PR TITLE
Release Candidate/0.0.1-RCXX

### PR DESCRIPTION
**Pull request by W3stside**
# Changes (queue Tupac)

1. Total Claimable Deposits fixed (broken due to BN bug - commented on open issue here: https://github.com/indutny/bn.js/issues/213)
2. Dont show countdown when time is over/negative
3. Show wallet on load
4. Fixed broken WETH/ETH balance in pool

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr6--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr6--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr6--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr6--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr6--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr6--dxmgnpoolreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]
All UI issues in one fell swoop :clap:

**Pull request merged**
