### PR TITLE
Release Candidate / 0.0.1-RC15

### PR DESCRIPTION
**Pull request by W3stside**
## Changes

1. fixed `NaN` countdown showing on load
2. Lock MGN shows amt lockable + hides if no MGN balance
3. CSS
4. Spinner svg
5. Further Countdown logic fixes
6. Upgraded to @gnosis.pm/dx-mgn-pool@0.1.3-RC3
7. Added SVG support webpack

**_Note - Keeping open for now_

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr8--dxmgnpoolreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]
Cool spinner!

**Pull request merged**
